#! /usr/bin/env python

""" Workflow for multi domain upscaling of a GEOS MPM DNS of an elastic cylinder under uni-axial stress in compression
Requires the following ``Sconscript(..., exports=[])``
* ``env`` - The SCons construction environment with the following required keys
  * ``DNS_GEOS_abspath`` - String absolute path to model_package/DNS_GEOS
  * ``filter_source_abspath`` - String absolute path to model_package/Filter
  * ``model_package_abspath`` - String absolute path to model_package
  * ``peta_data_copy_abspath`` - String absolute path to peta_data_copy
  * ``cubit`` - String absolute path to Cubit Python intepreter, optional
  * ``selected_parameter_sets`` - Optional string of space separated integers specifying which parameters sets should be considered for filtering, calibrating, and performing macroscale simulations
  * ``filter`` - Boolean speciyfing whether or not to run micromorphic filter for a particular upscaling study
  * ``calibrate`` - Boolean speciyfing whether or not to run calibration for a particular upscaling study
  * ``macro`` - Boolean speciyfing whether or not to run macro simulation(s) in Tardigrade-MOOSE
"""

import pathlib

import waves
import numpy

from model_package.DNS_GEOS import simulation_variables_nominal


# Inherit the parent construction environment
Import('env')

# set project-wide paths with os-agnostic path separators
DNS_GEOS_abspath = pathlib.Path(env["DNS_GEOS_abspath"])
filter_source_abspath = pathlib.Path(env["filter_source_abspath"])
model_package_abspath = pathlib.Path(env["model_package_abspath"])
peta_data_copy_abspath = pathlib.Path(env["peta_data_copy_abspath"])

# Simulation variables
build_directory = pathlib.Path(Dir('.').abspath)
workflow_name = build_directory.name
output_file_type = "h5"
model = "GEOS_I43_01_annular"
params = simulation_variables_nominal.I43_01

# Collect the target nodes to build a concise alias for all targets
workflow = []

# specify targets for visualizing Micromorphic Filter output
viz_targs =  (
    ('plot-stress-norms', 'stress_norms.png'),
    ('plot-better-stress-norms', 'better_stress_norms.png'),
    ('plot-best-stress-norms', 'best_stress_norms.png'),
    ('plot-norm-histories', 'norm_histories.png'),
    ('p-q-plots', 'p_q_plots.png'),
    ('csv-cauchy', 'cauchy.csv'),
    ('csv-PK2', 'PK2.csv'),
    ('csv-GLstrain', 'GLstrain.csv'),
    ('csv-estrain', 'estrain.csv'),
    ('csv-ref-mod', 'ref_moduli.csv'),
    ('csv-cur-mod', 'cur_moduli.csv'),
    ('csv-symm', 'symm.csv'),
    ('csv-stress-diff', 'stress_diff.csv'),
    ('csv-m', 'm_stress.csv'),
    ('csv-M', 'M_stress.csv'),
    ('csv-stress33-all', 'all_33_stresses.csv'),
    )
params['viz_targs'] = viz_targs

# ---------- Process existing DNS ----------------------------------------------
DNS_fileroot = f"{peta_data_copy_abspath}/{params['DNS_fileroot']}/"
results_file = params['DNS_file']

# TODO: remove background grid data before filter prep

# percent of radius to include in annular portion of geometry
annulus = 0.10
params['annulus'] = annulus

# Filter prep - Extract results to XDMF
main_XDMF_name = f"FILTER_INPUT_{model}"
filter_inputs = [f"{main_XDMF_name}.{ext}" for ext in ['xdmf', 'h5']]
cauchy_stresses = "DNS_all_33_stresses.csv"
XDMF_script = "vtk_to_xdmf_fast_multi.py"
script_options = f"--input-file {results_file}"
script_options += f" --file-root {DNS_fileroot}"
script_options += f" --output-file {str(build_directory / main_XDMF_name)}"
script_options += " --dist-factor 1"
script_options += " --stress-factor 1000."
script_options += " --density-factor 1.e-9"
script_options += f" --annulus-ratio {annulus}"
workflow.extend(env.PythonScript(
    target=filter_inputs,
    source=[str(DNS_GEOS_abspath / XDMF_script), f'{DNS_fileroot}/{results_file}'],
    script_options=script_options))
#params['homogenize_damage'] = True

# Get bounding information from DNS extents
bounding_csv = f"{model}_bounds.csv"
bounding_script = "bounds_from_DNS.py"
script_options = f"--dns-file {filter_inputs[0]}"
script_options += f" --output-file {bounding_csv}"
workflow.extend(env.PythonScript(
    target=bounding_csv,
    source=[str(filter_source_abspath / bounding_script)] + filter_inputs,
    script_options=script_options))

# TODO: bounds from background grid are larger than material points, figure out how to force the correct sized cylinder
rad = 0.5*params['diam']
bounding_csv = f"{model}_forced_bounds.csv"
bounding_script = "force_bounds.py"
script_options = f"--output-file {bounding_csv}"
#script_options += f" --xmin {-1*rad} --xmax {rad} --ymin {-1*rad} --ymax {rad} --zmin 0 --zmax {params['height']}"
zmin = 0.702705306122449 - 0.03125
zmax = 4.950168489795918 + 0.03125
script_options += f" --xmin {-1*rad} --xmax {rad} --ymin {-1*rad} --ymax {rad} --zmin {zmin} --zmax {zmax}"
workflow.extend(env.PythonScript(
    target=bounding_csv,
    source=[str(filter_source_abspath / bounding_script)],
    script_options=script_options))

params['bounding_csv'] = str(build_directory / bounding_csv)
filter_inputs = [f"{str(build_directory / main_XDMF_name)}.{ext}" for ext in ['xdmf', 'h5']]

# Post-processing step - force vs. displacement
plot_script = "plot_force_displacement.py"
force_results = f"{DNS_fileroot}/{params['DNS_forces']}"
force_plot_targets = [f"{model}_force_displacement.png", f"{model}_force_displacement.csv"]
script_options = f"--csv-file {force_results}"
script_options += f" --output-file {force_plot_targets[0]}"
script_options += f" --output-csv {force_plot_targets[1]}"
script_options += " --force-col ' Rz+'"
script_options += " --length-col ' length_z'"
script_options += " --header-row 0"
script_options += " --force-factor -1000 --disp-factor -1"
script_options += " --filter-markers 0 200 400 600 800 1000 1200 1400 1600"
workflow.extend(env.PythonScript(
    target=[force_plot_targets],
    source=[str(DNS_GEOS_abspath / plot_script)],
    script_options=script_options,
    ))

# # # Get image of DNS results
# # paraview_script= "get_paraview_image.py"
# # paraview_image = f"{model}_Cauchy.png"
# # script_options = f"--input-file {results_files[-1]}"
# # script_options += f" --output-file {paraview_image}"
# # script_options += " --field diagnostic_quantitiesprojected.Cauchy_stress_zz"
# # script_options += " --field-min -10.0 --field-max 0.0"
# # script_options += " --legend-title 'Cauchy Stress 33 (MPa)'"
# # workflow.extend(env.ParaviewImage(
    # # target=paraview_image,
    # # source=[str(model_package_abspath / paraview_script)] + results_files,
    # # script=str(model_package_abspath / paraview_script),
    # # script_options=script_options))

# ---------- MULTI-DOMAIN ------------------------------------------------------
# setup several options for different studies
parameter_schema = dict(
    parameter_samples = numpy.array([
        [2.5, 16],
        [1.5, 48],
        [0.75, 120],
        [0.55, 224],
        [0.4, 360],
        [0.25, 1080],
        [0.175, 4242],
        [0.1, 20064],
        ], dtype=object),
    parameter_names = numpy.array(["seed_size", "num_domains"])
)

parameter_flag = False
if env['selected_parameter_sets'] != "All":
    parameter_flag = True
    selected_parameter_sets = [int(i) for i in env['selected_parameter_sets'].split(' ')]

parameter_generator = waves.parameter_generators.CustomStudy(parameter_schema)
for set_name, parameters in parameter_generator.parameter_study_to_dict().items():

    # Optionally skip certain parameter sets
    if parameter_flag == True:
        set = int(str(set_name).split('parameter_set')[-1])
        if set not in selected_parameter_sets:
            continue

    set_name = pathlib.Path(set_name)

    domain_number = parameters['num_domains']
    seed_size = parameters['seed_size']

    filter_results = f"FILTER_RESULTS_{model}_{int(domain_number)}"
    filter_targs = [f"{filter_results}.{ext}" for ext in ['xdmf', 'h5']]
    params['filter_targs'] = filter_targs

    # ---------- FILTER --------------------------------------------------------
    # Run common filter sconscript
    if env['filter']:
        variant_dir = build_directory / set_name
        workflow.extend(
            SConscript("filter_annular.scons", variant_dir=variant_dir,
                       exports=["env", "parameters", "workflow_name", "model", "params", "filter_inputs"],
                       duplicate=False))

# Collector alias based on parent directory name
env.Alias(workflow_name, workflow)
