#! /usr/bin/env python

""" Workflow for multi domain upscaling the inelastic Ratel I43.09 DNS
Requires the following ``Sconscript(..., exports=[])``
* ``env`` - The SCons construction environment with the following required keys
  * ``DNS_Ratel_abspath`` - String absolute path to model_package/DNS_Ratel
  * ``filter_source_abspath`` - String absolute path to model_package/Filter
  * ``model_package_abspath`` - String absolute path to model_package
  * ``peta_data_copy_abspath`` - String absolute path to peta_data_copy
  * ``cubit`` - String absolute path to Cubit Python intepreter, optional
  * ``selected_parameter_sets`` - Optional string of space separated integers specifying which parameters sets should be considered for filtering, calibrating, and performing macroscale simulations
  * ``filter`` - Boolean speciyfing whether or not to run micromorphic filter for a particular upscaling study
  * ``calibrate`` - Boolean speciyfing whether or not to run calibration for a particular upscaling study
  * ``macro`` - Boolean speciyfing whether or not to run macro simulation(s) in Tardigrade-MOOSE
  * ``macro_platen`` - Boolean speciyfing whether or not to run macro simulation in Tardigrade-MOOSE with loading platens
  * ``macro_damage`` - Boolean speciyfing whether or not to run plastic macro simulation in Tardigrade-MOOSE gradient enhanced damage
  * ``summary`` - Boolean speciyfing whether or not to run summary post-processing for multi-domain studies
"""

import pathlib

import waves
import numpy

from model_package.DNS_Ratel import simulation_variables_nominal


# Inherit the parent construction environment
Import('env')

# set project-wide paths with os-agnostic path separators
DNS_Ratel_abspath = pathlib.Path(env["DNS_Ratel_abspath"])
filter_source_abspath = pathlib.Path(env["filter_source_abspath"])
model_package_abspath = pathlib.Path(env["model_package_abspath"])
peta_data_copy_abspath = pathlib.Path(env["peta_data_copy_abspath"])

# Simulation variables
build_directory = pathlib.Path(Dir('.').abspath)
workflow_name = build_directory.name
output_file_type = "h5"
model = "I43_09_best_DNS"
params = simulation_variables_nominal.I43_best_DNS

# Collect the target nodes to build a concise alias for all targets
workflow = []

# specify targets for visualizing Micromorphic Filter output
viz_targs =  (
    ('plot-cauchy-couple', 'cauchy_couple.png'),
    ('plot-stress-norms', 'stress_norms.png'),
    ('plot-better-stress-norms', 'better_stress_norms.png'),
    ('plot-best-stress-norms', 'best_stress_norms.png'),
    ('plot-norm-histories', 'norm_histories.png'),
    ('p-q-plots', 'p_q_plots.png'),
    ('csv-cauchy', 'cauchy.csv'),
    ('csv-PK2', 'PK2.csv'),
    ('csv-GLstrain', 'GLstrain.csv'),
    ('csv-estrain', 'estrain.csv'),
    ('csv-ref-mod', 'ref_moduli.csv'),
    ('csv-cur-mod', 'cur_moduli.csv'),
    ('csv-symm', 'symm.csv'),
    ('csv-stress-diff', 'stress_diff.csv'),
    ('csv-m', 'm_stress.csv'),
    ('csv-M', 'M_stress.csv'),
    ('csv-stress33-all', 'all_33_stresses.csv'),
    ('plot-stress-diff', 'stress_diff.png'),
    ('plot-rotation-diff', 'rotation_diff.png'),
    ('plot-stretch-diff', 'stretch_diff.png'),
    )
params['viz_targs'] = viz_targs

# ---------- Process existing DNS ----------------------------------------------
results_files = [f"{peta_data_copy_abspath}/{file.split('/')[-1]}" for file in params['DNS_files']]

# Filter prep - Extract results to XDMF
main_XDMF_name = f"FILTER_INPUT_{model}"
filter_inputs = [f"{main_XDMF_name}.{ext}" for ext in ['xdmf', 'h5']]
cauchy_stresses = "DNS_all_33_stresses.csv"
XDMF_script = "cgns_to_xdmf.py"
script_options = f"--input-files {' '.join(results_files)}"
script_options += f" --output-file {str(build_directory / main_XDMF_name)}"
script_options += " --dist-factor 0.001"
script_options += " --stress-factor 1."
script_options += " --density-factor 1.e-12"
script_options += " --damage True"
workflow.extend(env.PythonScript(
    target=filter_inputs,
    source=[str(DNS_Ratel_abspath / XDMF_script)] + results_files,
    script_options=script_options))

# Get bounding information from DNS extents
bounding_csv = f"{model}_bounds.csv"
bounding_script = "bounds_from_DNS.py"
script_options = f"--dns-file {filter_inputs[0]}"
script_options += f" --output-file {bounding_csv}"
workflow.extend(env.PythonScript(
    target=bounding_csv,
    source=[str(filter_source_abspath / bounding_script)] + filter_inputs,
    script_options=script_options))
params['bounding_csv'] = str(build_directory / bounding_csv)
filter_inputs = [f"{str(build_directory / main_XDMF_name)}.{ext}" for ext in ['xdmf', 'h5']]

# Post-processing step - force vs. displacement
plot_script = "plot_force_displacement.py"
force_results = f"{peta_data_copy_abspath}/{params['DNS_forces'].split('/')[-1]}"
force_plot_targets = [f"{model}_force_displacement.png", f"{model}_force_displacement.csv"]
script_options = f"--csv-file {force_results}"
script_options += f" --output-file {force_plot_targets[0]}"
script_options += f" --output-csv {force_plot_targets[1]}"
script_options += " --face-id 3"
script_options += " --final-disp 0.220"
script_options += " --header-row 0"
script_options += " --force-factor 1.e-6"
script_options += " --filter-markers 0 10 20 30 40 50 100 150 200 225 250 275 300 350 400 450 500"
workflow.extend(env.PythonScript(
    target=[force_plot_targets],
    source=[str(DNS_Ratel_abspath / plot_script), force_results],
    script_options=script_options,
    ))

# # Get image of DNS results
# paraview_script= "get_paraview_image.py"
# paraview_image = f"{model}_Cauchy.png"
# script_options = f"--input-file {results_files[-1]}"
# script_options += f" --output-file {paraview_image}"
# script_options += " --field diagnostic_quantitiesprojected.Cauchy_stress_zz"
# script_options += " --field-min -10.0 --field-max 0.0"
# script_options += " --legend-title 'Cauchy Stress 33 (MPa)'"
# workflow.extend(env.ParaviewImage(
    # target=paraview_image,
    # source=[str(model_package_abspath / paraview_script)] + results_files,
    # script=str(model_package_abspath / paraview_script),
    # script_options=script_options))

# # ---------- FILTER ------------------------------------------------------------
# setup several options for different studies
if params['cut'] == False:
    if 'cubit' not in env.keys():
        raise NotImplementedError("Without access to Cubit, this workflow can not be completed!")
    parameter_schema = dict(
        parameter_samples = numpy.array([
            [5.0, 1],
            [2.5, 4],
            [1.5, 42],
            #[1.0, 128],
            [0.75, 282],
            [0.5, 837],
            [0.375, 1908],
            #[0.25, 6480],
            ], dtype=object),
        parameter_names = numpy.array(["seed_size", "num_domains"])
    )
elif params['cut'] == True:
    parameter_schema = dict(
        parameter_samples = numpy.array([
            [5.0, 1],
            [2.5, 24],
            [1.5, 48],
            #[1.0, 128],
            [0.75, 264],
            [0.5, 768],
            [0.375, 2160],
            #[0.25, 6912],
            ], dtype=object),
        parameter_names = numpy.array(["seed_size", "num_domains"])
    )
else:
    print('Specify valid option!')

parameter_flag = False
if env['selected_parameter_sets'] != "All":
    parameter_flag = True
    selected_parameter_sets = [int(i) for i in env['selected_parameter_sets'].split(' ')]

parameter_generator = waves.parameter_generators.CustomStudy(parameter_schema)
for set_name, parameters in parameter_generator.parameter_study_to_dict().items():

    # Optionally skip certain parameter sets
    if parameter_flag == True:
        set = int(str(set_name).split('parameter_set')[-1])
        if set not in selected_parameter_sets:
            #print(f'Skipping {model} parameter_set{set}!')
            continue

    set_name = pathlib.Path(set_name)

    domain_number = parameters['num_domains']
    seed_size = parameters['seed_size']

    filter_results = f"FILTER_RESULTS_{model}_{int(domain_number)}"
    filter_targs = [f"{filter_results}.{ext}" for ext in ['xdmf', 'h5']]
    params['filter_targs'] = filter_targs

    # ---------- FILTER ---------------------------------------------------------------
    # Run common filter sconscript
    if env['filter']:
        variant_dir = build_directory / set_name
        workflow.extend(
            SConscript("filter.scons", variant_dir=variant_dir,
                       exports=["env", "parameters", "workflow_name", "model", "params", "filter_inputs"],
                       duplicate=False))

    # ---------- CALIBRATE ------------------------------------------------------------
    # Run common elasticity calibration sconscript
    filter_file = str(build_directory / set_name / filter_targs[0])
    params['filter_file'] = filter_file
    if env['calibrate_elasticity']:
        variant_dir = build_directory / set_name
        workflow.extend(
            SConscript("calibrate_element_elasticity.scons", variant_dir=variant_dir,
                       exports=["env", "parameters", "workflow_name", "model", "params"],
                       duplicate=False))
    # Run common plasticity calibration sconscript
    if env['calibrate_plasticity']:
        variant_dir = build_directory / set_name
        workflow.extend(
            SConscript("calibrate_element_plasticity.scons", variant_dir=variant_dir,
                       exports=["env", "parameters", "workflow_name", "model", "params"],
                       duplicate=False))
    case = params['plastic_calibration_case']
    params['calibration_map'] = f'{build_directory}/{set_name}/Calibration_map_plastic_parameters_case_{case}_{domain_number}.csv'

    # ---------- Tardigrade-MOOSE --------------------------------------------------
    # Run common Tardigrade-MOOSE sconscript
    if env['macro']:
        variant_dir = build_directory / set_name
        workflow.extend(
            SConscript("tardigrade_moose_plastic.scons", variant_dir=variant_dir,
                       exports=["env", "parameters", "workflow_name", "model", "params"],
                       duplicate=False))
    if env['macro_platen']:
        variant_dir = build_directory / set_name
        workflow.extend(
            SConscript("tardigrade_moose_plastic_platens.scons", variant_dir=variant_dir,
                       exports=["env", "parameters", "workflow_name", "model", "params"],
                       duplicate=False))
    if env['macro_damage'] and domain_number != 1:
        variant_dir = build_directory / set_name
        workflow.extend(
            SConscript("tardigrade_moose_plastic_damage.scons", variant_dir=variant_dir,
                       exports=["env", "parameters", "workflow_name", "model", "params"],
                       duplicate=False))

# ---------- Collect Results across Studies ------------------------------------
# Run common post-processing sconscript
if env['summary']:
    study = parameter_generator.parameter_study_to_dict()
    set_names = [pathlib.Path(set_name) for set_name, _ in study.items()]
    num_domains = [str(study[key]['num_domains']) for key in study.keys()]
    dns_forces = force_plot_targets[1]

    workflow.extend(
        SConscript("summarize_multi_domain.scons",
                   exports=["env", "workflow_name", "model", "params", "set_names", "num_domains", "dns_forces"],
                   duplicate=False))

# Collector alias based on parent directory name
env.Alias(workflow_name, workflow)
